# @package _group_

# log frequency
val_check_interval: 1.0
progress_bar_refresh_rate: 100

wandb:
  project: sketchsampler
  entity: USER

  watch:
    log: 'all'
    log_freq: 100

lr_monitor:
  logging_interval: "step"
  log_momentum: False
